version: '3'
services:
  app:
    restart: always
    build: ./app
    ports: 
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app/src:/src
    privileged: true

  db:
    image: mysql:5.6
    command: mysqld
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "33360:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cake
